apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.metadata.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.name }}
    spec:
      {{ if .Values.imagePullSecrets }}
      imagePullSecrets: 
      {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{ end }}
      containers:
      - name: {{ .Values.metadata.name }}
        {{ toYaml .Values.image | nindent 8 }}
        ports:
        - containerPort: {{ .Values.targetPort }}
