apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.metadata.name }}
data:
  maintainer: {{ .Values.metadata.maintainer }}
  description: {{ .Values.metadata.description }}
