apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports: 
  - name: http-port
    port: {{ .Values.port }}
    targetPort: {{ .Values.targetPort }}
  selector:
    app: {{ .Values.metadata.name }}
